# @package _group_

name: mix_image
gap: 0 # gap between images
image_type: 
  - sine_wave_high #moving image. mnist, cifar10, sine_wave, 
  - sine_wave_low #static image. mnist, cifar10, sine_wave,
num_data: 5000
num_frames: 10
img_width: 128
img_channel: 1
max_intensity: 1
grey_scale: True # if true save grey scale gif 

motions: # motion to use (transition, rotation, growth_decay)
  - transition