# @package _group_

name: moving_mnist
num_data: 4
num_frames: 10
img_width: 128
img_channel: 1
max_intensity: 1
grey_scale: False # if true save grey scale gif 

motions: # motion to use (transition, rotation, growth_decay)
  - transition
  - rotation
  - growth_decay