# @package _group_

name: moving_image
image_type: mnist #moving image. mnist or cifar10
num_data: 5000
num_frames: 10
img_width: 128
img_channel: 1
max_intensity: 1
grey_scale: True # if true save grey scale gif 

motions: # motion to use (transition, rotation, growth_decay)
  - transition