
output_dir: Unet
mlrun_path: /home/data/ryoto/Unet/mlruns/
experiment:
  name: Mnist
dataset: 
  num_data: 100
  len_seq: 20
  input_num: 4
  motions: # motion to use (transition, rotation, growth_decay)
    - transition
    - rotation
    - growth_decay
# Training configs
train:
  epochs: 100
  batch_size: 8
  device: cuda:1
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  lr: 0.0001
  val_percent: 0.1 # Percent of the data that is used as validation (0-1)

# Model configs
model:
  load: False
test:
  load_model: "/home/data/ryoto/Unet/mlruns/2/e8ab44a681604eb9aaac31c6a4b26bfd/artifacts/best_ckpt.pth" # Load model from a .pth file
  batch_size: 8
  device: cuda:1
  num_workers: 2
scale: 0.5 # Downscaling factor of the images