
defaults:
 - dataset: human_action
mlrun_path: /home/data/ryoto/Result/mlruns/
experiment:
  name: Unet
# Training configs
train:
  epochs: 50
  batch_size: 16
  device: cuda:1
  save_best_ckpt: True
  num_save_images: 3  # of images saved per checkpoint
  num_workers: 2
  ckpt_path: best_ckpt.pth
  lr: 0.0001
  val_percent: 0.3 # Percent of the data that is used as validation (0-1)

# Model configs
model:
  input_num: 10
  load: False
test:
  load_model: "/home/data/ryoto/Unet/mlruns/2/e8ab44a681604eb9aaac31c6a4b26bfd/artifacts/best_ckpt.pth" # Load model from a .pth file
  batch_size: 8
  device: cuda:1
  num_workers: 2
scale: 0.5 # Downscaling factor of the images