# Default project 

# Import presets
defaults:
  - hydra: custom

# Dir name
output_dir: ExperimentTemplate
mlrun_path: /data/${output_dir}/mlruns/

# MLflow configs
experiment:
  name: weather
# Training configs
train:
  batch_size: 10
  epochs: 20
  save_best_ckpt: True
  num_workers: 2
  eval: False
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
