# @package _group_

name: training
epochs: 30
batch_size: 16
device: cuda:2
save_best_ckpt: True
num_save_images: 3  # of images saved per checkpoint
num_workers: 16
ckpt_path: best_ckpt.pth
lr: 0.0001
val_percent: 0.3 # Percent of the data that is used as validation (0-1)
